server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gabrielmendes17/config-repo/
        #  username: 
        #  password: 
          search-paths: 
          - app*
          force-pull: true
       # encrypt:
         # enabled: false